### PR TITLE
TokenizerBuilder

### PR DESCRIPTION
**Pull request by epwalsh**
What do you think @n1t0?

### CODE REVIEW

**Comment by sai-prasanna** [comment]
There is a `derive-builder` macro, which makes creating builders trivial. Can we explore that?

https://github.com/colin-kiegel/rust-derive-builder

Usage in the wild

https://github.com/reneklacan/symspell/blob/master/src/symspell.rs#L22

**Comment by epwalsh** [comment]
@sai-prasanna I like that! Could potentially remove a whole lot of boilerplate. I'll take a look

**Comment by epwalsh** [comment]
@sai-prasanna would you be interested in making a PR to see if that works for replacing the other manually implemented builders (such as in the `src/models/*` modules)?

**Comment by sai-prasanna** [comment]
@epwalsh Sure, will try to do it next weekend if I have time. Bit busy the following week.

**Comment by n1t0** [comment]
This is out of date

**Pull request closed without merging**
