### PR TITLE
Bump spm_precompiled to 0.1.3

### PR DESCRIPTION
**Pull request by MikeIvanichev**
As it stands now using spm_precompiled < 0.1.3 will result in the build of tokenizers failing.
While by default cargo will pick the newest available version for all dependencies, if a user has not run `cargo update` in a while they can still have older versions in their lock file.

This error can be reproduced by running `rustup run nightly cargo update -Zminimal-versions && cargo --locked check`, creating a lock file with minimal versions of all dependencies allowed by Cargo.toml.

It may also be a good idea to add such a check to the CI, if you think this would be a valuable addition, let me know, and I'll be happy to do it.

### CODE REVIEW

**Comment by MikeIvanichev** [comment]
Ant chance the Node / check is a spurious failure, or unrelated to this pr? 
Dont have much experiance with NodeJs.

**Review by ArthurZucker — COMMENTED** [review]
LGTM but I have no idea why node is failing either!

**Comment by ArthurZucker** [comment]
Could you rebase on main? If it keeps failing it means it's probably incompatible

**Comment by MikeIvanichev** [comment]
Rebased

**Review by Narsil — APPROVED** [review]

**Pull request merged**
