### PR TITLE
WIP: Bump `pyo3` version to `v0.22`

### PR DESCRIPTION
**Pull request by sydney-runkle**
Closes https://github.com/huggingface/tokenizers/issues/1639

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Would be nice if it was this easy 😅 super welcome btw thanks 🤗 

I'll work a bit on that if I can but last time I checked there was a lot of issues

**Comment by yookoala** [comment]
The conflict was caused by https://github.com/PyO3/rust-numpy 0.21. Their [version 0.22](https://github.com/PyO3/rust-numpy/releases/tag/v0.22.0) would update the pyo3 version requirement to 0.22, which would probably solve the remaining problem here.

Updating [this](https://github.com/huggingface/tokenizers/blob/9b77c054ef4297c7057fa8db875368c7c02f1bfc/bindings/python/Cargo.toml#L18) to "0.22" should probably fix the checks and the builds here.

**Comment by diliop** [comment]
Taking a stab at doing this in https://github.com/huggingface/tokenizers/pull/1665, would love some feedback

**Comment by yookoala** [comment]
Since #1665 is merged, this is no longer necessary. Please close this one.

**Pull request closed without merging**
