### PR TITLE
feat(ci): add macos arm64 runner

### PR DESCRIPTION
**Pull request by McPatate**
I've added an arm64 runner that you can check out in the settings tab.

Edited the CI to make it release arm64 bins !

### CODE REVIEW

**Comment by Narsil** [comment]
Do you mind creating an actions where this actually ran to check what actually happened.

Just comment out the upload to pypi part, so we can iterate on it.

**Comment by Narsil** [comment]
Arm64 node build can be ignored. If you can just remove it from the automated build that'd be ok :)

We need to rewrite the node bindings at some point anyway (but seems like a lot of efforts :( )

**Comment by McPatate** [comment]
> We need to rewrite the node bindings at some point anyway (but seems like a lot of efforts :( )

Does anyone use them ?

**Comment by Narsil** [comment]
> Does anyone use them ?

There are some issues open yes, but as we're lagging behind in node versions it's harder and harder to use them
https://github.com/huggingface/tokenizers/issues?q=is%3Aissue+is%3Aopen+node

**Comment by Narsil** [comment]
Let's close in favor of https://github.com/huggingface/tokenizers/pull/1055 if you're OK with it.

**Pull request closed without merging**
