### PR TITLE
Added ability to inspect a 'Sequence' decoder and the `AddedVocabulary`.

### PR DESCRIPTION
**Pull request by eaplatanios**
This PR is in similar spirit to #1341 and adds a couple more functions that allow one to construct a modified version of an existing `Tokenizer`. I've followed the existing style and conventions for newly introduced functions.

### CODE REVIEW

**Comment by eaplatanios** [comment]
@ArthurZucker @Narsil gentle ping about this PR. This PR should not be controversial and is in similar spirit to #1341 (and has the same motivation).

**Comment by ArthurZucker** [comment]
really sorry about all the delays, lot happening on transformers, I'll free some time

**Review by ArthurZucker — APPROVED** [review]
Actually doesn't look bad and would help me in transformers if we add the layer to update the added vocab. This is not super stateless, so leave it up to @Narsil

**Review by Narsil — APPROVED** [review]
LGTM.

It's ok because it doesn´t seem like we open up any function that have potentially bad internal state (Deserialize is not implemented for AddedVocabulary directly, itś always parsed from the entire Tokenizer).

**Comment by ArthurZucker** [comment]
Thanks for your contribution 🤗

**Pull request merged**
