### PR TITLE
Python - update pyo3 and start using new API

### PR DESCRIPTION
**Pull request by ljos**
This should work with the new API (if it stays the way it is) of pyo3 when it is ready.

### CODE REVIEW

**Comment by n1t0** [comment]
Hey @ljos! PyO3 is now out of alpha. They recently released the `0.9.1`. Would you be willing to update this with the last version of `master`? Sorry, a lot of things have changed!

**Comment by ljos** [comment]
I'll have a look

**Comment by ljos** [comment]
I think I have gotten the gist of it. There are some things that are a little more difficult than others, though I think I will be able to fix them. I will look at it tomorrow or/and in the weekend.

**Comment by ljos** [comment]
I haven't actually run  this as I get some linking error on my work computer. I am not sure what is up there. It does seem to compile as the GitHub action gives me the green checkmark, but I haven't been able to run it and see if it actually works. I don't see that there are any tests in the python part of the repo. There are the examples, but I don't see that those are run on the actions.

**Comment by n1t0** [comment]
Thank you for the update @ljos, I'll have a look, probably today. Unfortunately, there aren't any tests on the Python side for now, we plan on adding this really soon though.

If you are trying to build on windows, and have a link error there, this might help you: https://github.com/huggingface/tokenizers/issues/135

**Comment by ljos** [comment]
I am on macOS and I think it might be an update issue from homebrew or something...

**Comment by ljos** [comment]
pip install -e works, but cargo build doesn't. Probably something strange about my environment. I found an error. The creation of a new empty model doesn't work the way I thought it should so that leaves a type error right now. I have a solution that works, but I am trying to find a solution that keeps the type information. What I am trying to do is to make BPE.empty() returns a BPE model and not a Model.

**Comment by ljos** [comment]
I the commit I just pushed I fix this issue, but I am not completely satisfied as it removes type information. I will see what I can do tomorrow.

**Comment by n1t0** [comment]
Oh I see. `cargo build` also fails sometimes for me, I think it might be expected. I found the easiest dev setup was to use `maturin develop [--release]` (you can install it with pip). I also have some problems with `pip` and `python setup.py [install | build]` sometimes.

I quickly looked at the problem for `from_files` and `empty` and I think we can just use `#[new]` with them too. It should then work just like for any other constructor.

I also expect to merge the python tests (https://github.com/huggingface/tokenizers/pull/213) soon, so we'll be able to test all of this!

**Comment by ljos** [comment]
Changing the models to use the new initialiser does look nicer to my eyes. Review my latest commit, and if you a agree I'll change the type data etc in python to match the new API. Maybe you want to still keep the old API?

**Comment by n1t0** [comment]
At first, I wanted to keep the old API because I thought it would be easier to add more constructors, for example, to initialize directly from memory with the vocab/merges dicts, ...
But in the end, I also find this API way nicer and more Pythonic, and we could probably use exactly the same one to provide dicts instead of strings. What do you think?

**Comment by ljos** [comment]
Yes, I think if we wanted to we could have `vocab` and `merges` be either a string/file or a dict. We could also have arguments for providing dict and another set for providing files. If we want different construction methods I think we should either use subclassing or a builder pattern (like it is done in the main library).

**Comment by n1t0** [comment]
:+1: I'm really looking forward to merging this. I love the way PyO3 is evolving.

So, I think we miss the following before we can merge:
 - [ ] Update typings
 - [ ] Update tests to check that it keeps the initial type: example for BPE: `assert isinstance(BPE(), BPE)` along with the `isinstance(BPE(), Model)`
 - [ ] Update the CHANGELOG.md

**Comment by n1t0** [comment]
Thank you @ljos!

**Pull request merged**
