### PR TITLE
Fixing tokenizers with 1.53 (updated some dependencies + clippy)

### PR DESCRIPTION
**Pull request by Narsil**

### CODE REVIEW

**Review by SaulLu — APPROVED** [review]
Thank you so much for taking care of it! :+1:

**Comment by Narsil** [comment]
@n1t0 can you just check briefly please ?
(Had to update spm_precompiled which depends on nom which depends on lexical-core which had to be updated because of some compiler update (u32 and usize are not compatible anymore).

I simply ran `cargo update` as the specified versions work.

**Comment by Narsil** [comment]
@SaulLu I'll merge this so you can rebase in the meantime.

Cheers.

**Comment by SaulLu** [comment]
> @SaulLu I'll merge this so you can rebase in the meantime.
> 
> Cheers.

Thank you :hugs:

**Pull request merged**
