### PR TITLE
CD backports

### PR DESCRIPTION
**Pull request by chris-ha458**
follow
three commits that each implement
https://github.com/huggingface/safetensors/pull/312

https://github.com/huggingface/safetensors/pull/315

https://github.com/huggingface/safetensors/pull/317

@Narsil  do you think they should be separate PRs?
also how should I properly test them locally?
i'd hate to stress the PR build test infrastructure every time

### CODE REVIEW

**Comment by chris-ha458** [comment]
for `https://github.com/huggingface/safetensors/pull/312`
only a single node check fails.
I'll try what the compiler recommends but i'm not sure of it's downstream consequences. But here goes.

**Comment by Narsil** [comment]
Node is 12 and starting failing some time ago. I need to finish my node rewrite (which is done but I was fighting the distribution mecanism and couldn't make it work).

In the meantime we're effectively dropping node, it can't slow the rest down.

**Review by Narsil — APPROVED** [review]
LGTM

**Comment by chris-ha458** [comment]
should `upload_package:` be capitalized differently either here or on safe tensors?

**Comment by Narsil** [comment]
Not really why ? Just what you're doing here is fine, minimal changes in the same way.

**Comment by chris-ha458** [comment]
all tests besides the node pass!

**Comment by Narsil** [comment]
LGTM

**Pull request merged**
