### PR TITLE
Add `expect()` for disabling truncation

### PR DESCRIPTION
**Pull request by boyleconnor**
Addresses [this request](https://github.com/huggingface/tokenizers/pull/1306#discussion_r1275860309) by @Narsil

### CODE REVIEW

**Comment by Narsil** [comment]
LGTM, could you fix the format ?

**Comment by boyleconnor** [comment]
@Narsil just pushed, sorry I only ran the format checks on the main codebase, not the bindings

**Comment by boyleconnor** [comment]
@Narsil are you planning to review/approve this?

**Review by ArthurZucker — APPROVED** [review]
Looks good to me.

**Comment by boyleconnor** [comment]
@ArthurZucker @Narsil thank you for approving; I don't have permission to merge, so one of you will have to

**Pull request merged**
