### PR TITLE
More cache options.

### LINKED ISSUE #1539: Memory leak for large strings
This snippet will cause memory usage to rise indefinitely:

```python
from transformers import AutoTokenizer
import gc

tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0", use_fast=True)
refresh_every = 100000

for i in range(100000):
  s = f'{i} {i} ' * 10000
  tokenizer.encode(s)
  gc.collect()
  if i % 100 == 0:
    print(i)
  if i % refresh_every == 0:
    tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0", use_fast=True)
```

If you set `refresh_every` to 100000 (like it is in the snippet), the memory usage will keep on rising. [This colab notebook](https://colab.research.google.com/drive/1YDuPXviLqmwFAaROiVMCLIwPGjLTkQ_Y#scrollTo=3eIklMiRFq6J) crashes after about 15 minutes of executing.

If you set `refresh_every` to 100, the memory consumption will be stable.

### PR DESCRIPTION
**Pull request by Narsil**
Fixes #1539

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thanks, closed #1662!

**Comment by wangguanggg** [comment]
@Narsil @ArthurZucker excuse me, i am facing a memory leaks problem may caused by this. And could you help me to disable the cache in this version?
`from transformers import AutoTokenizer`
`tokenizer = AutoTokenizer.from_pretrained(_path)`
`tokenizer.backend_tokenizer.model.cache_capacity(0)`
This code cann't work.

**Comment by ArthurZucker** [comment]
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(_path)
tokenizer._tokenizer.model.cache_capacity(0)
```
where does `backend_tokenizer` come from?

**Comment by wangguanggg** [comment]
> ```python
> from transformers import AutoTokenizer
> tokenizer = AutoTokenizer.from_pretrained(_path)
> tokenizer._tokenizer.model.cache_capacity(0)
> ```
> 
> where does `backend_tokenizer` come from?

AttributeError: 'tokenizers.models.BPE' object has no attribute 'cache_capacity'

**Comment by ArthurZucker** [comment]
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(_path)
tokenizer._tokenizer.model._clear_cache()
```
or
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(_path)
tokenizer._tokenizer.model._resize_cache(0)
```

**Comment by ArthurZucker** [comment]
You can find the functions using `dir(tokenizer._tokenizer.model)`

**Comment by ArthurZucker** [comment]
do you want to open a PR to add some doc?

**Comment by wangguanggg** [comment]
> do you want to open a PR to add some doc?

no, i just won't to disable cache. but i only can do it by backend_tokenizer.

**Comment by ArthurZucker** [comment]
```
tokenizer._tokenizer.model._resize_cache(0)
```
will disable it

**Comment by ArthurZucker** [comment]
`backend_tokenizer` does not exist sir

**Comment by wangguanggg** [comment]
> `backend_tokenizer` does not exist sir

the tokenizers generated by transformers seems have.

**Comment by ArthurZucker** [comment]
No, the `backend_tokenizer` is `_tokenizer`

**Pull request merged**
