### PR TITLE
add ability to disable parallelism

### PR DESCRIPTION
**Pull request by epwalsh**
Addresses #187. Python tokenizers will now work within a sub-process as long as you disable parallelism:

```python
import sys
from multiprocessing import Process
from tokenizers.implementations import ByteLevelBPETokenizer

tok = ByteLevelBPETokenizer()
tok.encode("hi")
tok.encode_batch(["hi", "there"])


def encode():
    # Disabling parallelism is key to avoiding a dead lock within a sub-process.
    tok.parallelism = False
    print(tok.encode("hi"))
    print(tok.encode_batch(["hi", "there"]))


p = Process(target=encode)
p.start()

p.join(timeout=1)
if p.is_alive():
    print("process is hanging, killing now")
    p.terminate()
    sys.exit(1)
```

---

My original idea of having a custom trait for parallel iterators that would wrap `rayon` turned out to be way too complicated.

So instead I just added a `bool` option called `parallelism` to the `Tokenizer` struct, and threw in a check for this everywhere that `into_par_iter()` (or anything else like that from `rayon`) is used. So when `parallelism` is `false`, the non-parallel version (such as `into_iter()`) is used.

### CODE REVIEW

**Comment by epwalsh** [comment]
I don't know if this issue would arise in Node (and I don't know my way around Node anyway) so I haven't add anything to those bindings.

**Comment by n1t0** [comment]
Thank you for the PR @epwalsh! I'm sorry I didn't get a chance to work on this for now, as I wanted to check a few things, but I'll do my best to get it done asap.

Can you elaborate a bit on the difficulties you encountered while trying to wrap `.par_iter` and others in our own traits? I really liked the idea and would love to explore this a bit more if at all possible. I fear that we end up having to think about wrapping this manually everywhere otherwise, and having to carry the `parallelism` property everywhere might make things difficult in some cases.

**Comment by epwalsh** [comment]
No worries, take your time!

> Can you elaborate a bit on the difficulties you encountered while trying to wrap `.par_iter` and others in our own traits? I really liked the idea and would love to explore this a bit more if at all possible. I fear that we end up having to think about wrapping this manually everywhere otherwise, and having to carry the `parallelism` property everywhere might make things difficult in some cases.

The main complication I saw with trying to creating a custom `ParalleIterator` trait is that we'd have to implement it on every iterator struct that we use from both https://doc.rust-lang.org/std/iter/trait.Iterator.html and https://docs.rs/rayon/1.3.1/rayon/iter/trait.ParallelIterator.html. And then our custom trait methods would have to `Box` their output. This could get pretty ugly.

So since we only use the rayon trait method in a handfull of locations I figured - although not ideal - just manually wrapping would be much more tractable.

The other thing I realized is that the dead lock issue is not just with `rayon`. In fact, any attempt to access a `lazy_static` var after forking results in a dead lock. And so it seems like passing `parallelism` around is necessary, as opposed to having a global `STATIC` flag to disable parallelism that gets it's value from an environment variable.

(I also tried using a `STATIC` flag with `once_cell`, but saw the same issue)

**Comment by n1t0** [comment]
Indeed, I saw problems with `lazy_static` too, when digging #183. There was a deadlock when using the byte-level `PreTokenizer` even with `encode` since it uses it to generate the regex and the byte<->characters maps.

I'm surprised that it seems to work here, even though you added a test for byte-level BPE

**Comment by epwalsh** [comment]
Closing in favor of #311

**Pull request closed without merging**
