### PR TITLE
Use LTO for release and benchmark builds

### PR DESCRIPTION
**Pull request by csko**
Enable LTO optimizations for the release and benchmark build. 10-40% improvement based on the benchmark.

```
     Running benches\bert_benchmark.rs (target\release\deps\bert_benchmark-ab50c2abceb48f78.exe)
Benchmarking WordPiece BERT encode
Benchmarking WordPiece BERT encode: Warming up for 3.0000 s
Benchmarking WordPiece BERT encode: Collecting 20 samples in estimated 5.0023 s (225540 iterations)
Benchmarking WordPiece BERT encode: Analyzing
WordPiece BERT encode   time:   [22.069 µs 22.256 µs 22.429 µs]
                        change: [-43.858% -42.120% -40.433%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 20 measurements (15.00%)
  2 (10.00%) low mild
  1 (5.00%) high mild
slope  [22.069 µs 22.429 µs] R^2            [0.9891008 0.9894425]
mean   [21.775 µs 22.403 µs] std. dev.      [430.10 ns 945.35 ns]
median [21.931 µs 22.388 µs] med. abs. dev. [246.80 ns 912.87 ns]

Benchmarking WordPiece BERT encode batch
Benchmarking WordPiece BERT encode batch: Warming up for 3.0000 s
Benchmarking WordPiece BERT encode batch: Collecting 20 samples in estimated 5.4444 s (840 iterations)
Benchmarking WordPiece BERT encode batch: Analyzing
WordPiece BERT encode batch
                        time:   [6.1949 ms 6.2125 ms 6.2402 ms]
                        change: [-28.127% -26.776% -25.463%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 20 measurements (15.00%)
  2 (10.00%) high mild
  1 (5.00%) high severe
slope  [6.1949 ms 6.2402 ms] R^2            [0.9959444 0.9955571]
mean   [6.2414 ms 6.4360 ms] std. dev.      [113.95 µs 293.98 µs]
median [6.2016 ms 6.2940 ms] med. abs. dev. [15.562 µs 183.86 µs]

Benchmarking WordPiece Train vocabulary (small)
Benchmarking WordPiece Train vocabulary (small): Warming up for 3.0000 s
Benchmarking WordPiece Train vocabulary (small): Collecting 10 samples in estimated 5.6061 s (220 iterations)
Benchmarking WordPiece Train vocabulary (small): Analyzing
WordPiece Train vocabulary (small)
                        time:   [24.715 ms 24.796 ms 24.895 ms]
                        change: [-12.294% -10.375% -8.0660%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 10 measurements (30.00%)
  1 (10.00%) low mild
  2 (20.00%) high severe
slope  [24.715 ms 24.895 ms] R^2            [0.9984030 0.9983044]
mean   [24.750 ms 25.747 ms] std. dev.      [109.27 µs 1.3037 ms]
median [24.733 ms 25.417 ms] med. abs. dev. [27.664 µs 799.35 µs]

Benchmarking WordPiece Train vocabulary (big)
Benchmarking WordPiece Train vocabulary (big): Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 7.5s.
Benchmarking WordPiece Train vocabulary (big): Collecting 10 samples in estimated 7.5241 s (10 iterations)
Benchmarking WordPiece Train vocabulary (big): Analyzing
WordPiece Train vocabulary (big)
                        time:   [735.46 ms 740.17 ms 745.19 ms]
                        change: [-14.705% -13.977% -13.265%] (p = 0.00 < 0.05)
                        Performance has improved.
mean   [735.46 ms 745.19 ms] std. dev.      [3.6400 ms 11.235 ms]
median [736.12 ms 745.50 ms] med. abs. dev. [115.27 µs 14.248 ms]

     Running benches\bpe_benchmark.rs (target\release\deps\bpe_benchmark-0baeb34903957df4.exe)
Benchmarking BPE GPT2 encode
Benchmarking BPE GPT2 encode: Warming up for 3.0000 s
Benchmarking BPE GPT2 encode: Collecting 20 samples in estimated 5.0031 s (316050 iterations)
Benchmarking BPE GPT2 encode: Analyzing
BPE GPT2 encode         time:   [15.879 µs 16.016 µs 16.156 µs]
                        change: [-31.938% -30.681% -29.497%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 20 measurements (5.00%)
  1 (5.00%) high mild
slope  [15.879 µs 16.156 µs] R^2            [0.9909072 0.9908037]
mean   [15.683 µs 16.020 µs] std. dev.      [274.07 ns 483.27 ns]
median [15.695 µs 15.978 µs] med. abs. dev. [98.141 ns 702.20 ns]

Benchmarking BPE GPT2 encode batch
Benchmarking BPE GPT2 encode batch: Warming up for 3.0000 s
Benchmarking BPE GPT2 encode batch: Collecting 20 samples in estimated 5.7377 s (1050 iterations)
Benchmarking BPE GPT2 encode batch: Analyzing
BPE GPT2 encode batch   time:   [5.3231 ms 5.3427 ms 5.3663 ms]
                        change: [-25.950% -23.600% -21.823%] (p = 0.00 < 0.05)
                        Performance has improved.
slope  [5.3231 ms 5.3663 ms] R^2            [0.9975463 0.9973584]
mean   [5.3491 ms 5.4014 ms] std. dev.      [42.972 µs 75.008 µs]
median [5.3360 ms 5.4085 ms] med. abs. dev. [27.864 µs 102.34 µs]

Benchmarking BPE GPT2 encode, no cache
Benchmarking BPE GPT2 encode, no cache: Warming up for 3.0000 s
Benchmarking BPE GPT2 encode, no cache: Collecting 20 samples in estimated 5.0001 s (221760 iterations)
Benchmarking BPE GPT2 encode, no cache: Analyzing
BPE GPT2 encode, no cache
                        time:   [22.562 µs 22.644 µs 22.737 µs]
                        change: [-27.449% -26.762% -26.135%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 20 measurements (5.00%)
  1 (5.00%) high mild
slope  [22.562 µs 22.737 µs] R^2            [0.9973428 0.9972119]
mean   [22.559 µs 22.835 µs] std. dev.      [191.55 ns 429.07 ns]
median [22.511 µs 22.826 µs] med. abs. dev. [95.696 ns 429.56 ns]

Benchmarking BPE GPT2 encode batch, no cache
Benchmarking BPE GPT2 encode batch, no cache: Warming up for 3.0000 s
Benchmarking BPE GPT2 encode batch, no cache: Collecting 20 samples in estimated 5.7360 s (840 iterations)
Benchmarking BPE GPT2 encode batch, no cache: Analyzing
BPE GPT2 encode batch, no cache
                        time:   [6.7050 ms 6.7393 ms 6.7865 ms]
                        change: [-23.129% -22.631% -21.980%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 20 measurements (5.00%)
  1 (5.00%) high severe
slope  [6.7050 ms 6.7865 ms] R^2            [0.9940111 0.9932740]
mean   [6.7040 ms 6.7821 ms] std. dev.      [38.806 µs 140.88 µs]
median [6.6827 ms 6.7528 ms] med. abs. dev. [30.385 µs 89.564 µs]

Benchmarking BPE Train vocabulary (small)
Benchmarking BPE Train vocabulary (small): Warming up for 3.0000 s
Benchmarking BPE Train vocabulary (small): Collecting 10 samples in estimated 6.1949 s (275 iterations)
Benchmarking BPE Train vocabulary (small): Analyzing
BPE Train vocabulary (small)
                        time:   [22.302 ms 22.338 ms 22.378 ms]
                        change: [-15.050% -13.810% -12.611%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
slope  [22.302 ms 22.378 ms] R^2            [0.9998033 0.9997897]
mean   [22.282 ms 22.453 ms] std. dev.      [59.854 µs 193.35 µs]
median [22.276 ms 22.453 ms] med. abs. dev. [14.122 µs 248.66 µs]

Benchmarking BPE Train vocabulary (big)
Benchmarking BPE Train vocabulary (big): Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 7.4s.
Benchmarking BPE Train vocabulary (big): Collecting 10 samples in estimated 7.4178 s (10 iterations)
Benchmarking BPE Train vocabulary (big): Analyzing
BPE Train vocabulary (big)
                        time:   [730.65 ms 733.34 ms 737.08 ms]
                        change: [-16.088% -15.030% -14.086%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
mean   [730.65 ms 737.08 ms] std. dev.      [1.5432 ms 8.3653 ms]
median [729.93 ms 733.79 ms] med. abs. dev. [311.94 µs 6.2676 ms]

     Running benches\layout_benchmark.rs (target\release\deps\layout_benchmark-554038beabf945e0.exe)
Benchmarking TemplateProcessing single encode
Benchmarking TemplateProcessing single encode: Warming up for 3.0000 s
Benchmarking TemplateProcessing single encode: Collecting 20 samples in estimated 5.0005 s (2082150 iterations)
TemplateProcessing single encode
                        time:   [1.5679 µs 1.5796 µs 1.5950 µs]
                        change: [-21.510% -18.579% -15.576%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 20 measurements (10.00%)
  1 (5.00%) high mild
  1 (5.00%) high severe
slope  [1.5679 µs 1.5950 µs] R^2            [0.9882793 0.9869073]
mean   [1.5884 µs 1.6636 µs] std. dev.      [31.021 ns 129.12 ns]
median [1.5749 µs 1.6191 µs] med. abs. dev. [19.097 ns 73.304 ns]

Benchmarking TemplateProcessing pair encode
Benchmarking TemplateProcessing pair encode: Warming up for 3.0000 s
Benchmarking TemplateProcessing pair encode: Collecting 20 samples in estimated 5.0003 s (1114470 iterations)
Benchmarking TemplateProcessing pair encode: Analyzing
TemplateProcessing pair encode
                        time:   [3.1489 µs 3.1679 µs 3.2012 µs]
                        change: [-31.820% -27.564% -22.455%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 20 measurements (10.00%)
  1 (5.00%) high mild
  1 (5.00%) high severe
slope  [3.1489 µs 3.2012 µs] R^2            [0.9818992 0.9794425]
mean   [3.2179 µs 3.4932 µs] std. dev.      [104.61 ns 502.42 ns]
median [3.1554 µs 3.2941 µs] med. abs. dev. [40.175 ns 229.46 ns]
```

### CODE REVIEW

**Comment by chris-ha458** [comment]
https://doc.rust-lang.org/cargo/reference/profiles.html
AFAIK if the lto option is absent (as it currently is) lto defaults to "thin local LTO" aka "crate-local"
Your PR is for "fat" perform optimizations across all crates within the dependency graph. with significant compile time cost.
There is another option for "thin" LTO which is almost as good as "fat" but much faster.
Considering this, I think the following would be useful for the developers to make a decision wrt the PR

1. Benchmark both "thin" and "fat" for runtime (cargo bench)
2. Benchmark compile/ build times (cargo build --timings)

**Comment by chris-ha458** [comment]
since lto=false is default and not lto=off i think the latter is irrelevant for our purposes.
The following would be useful:

- [ ] RUSTFLAGS='-C lto=false' cargo bench>lto_false_bench.txt
- [ ] RUSTFLAGS='-C lto=thin' cargo bench > lto_thin_bench.txt
- [ ] RUSTFLAGS='-C lto=fat' cargo bench > lto_fat_bench.txt
- [ ] RUSTFLAGS='-C lto=false' cargo build --release --timings> lto_false_build.txt
- [ ] RUSTFLAGS='-C lto=thin' cargo build --release --timings> lto_thin_build.txt
- [ ] RUSTFLAGS='-C lto=fat' cargo build --release --timings> lto_fat_build.txt

bonus for devs
- [ ] RUSTFLAGS='-C lto=false' cargo build --timings> lto_false_build_dev.txt
- [ ] RUSTFLAGS='-C lto=thin' cargo build --timings> lto_thin_build_dev.txt
- [ ] RUSTFLAGS='-C lto=fat' cargo build --timings> lto_fat_build_dev.txt

**Comment by chris-ha458** [comment]
i don't know why but my above commands are meeting this error : 
error: options `-C embed-bitcode=no` and `-C lto` are incompatible
It's clear that OP had no such issue by toggling toml, so I'll have to follow that route.
Since the commit suggest only toggling the release profile, I shall do the same. 3 benches for 
False, Thin, Fat each

**Comment by chris-ha458** [comment]
I ran 4 tests consecutively 
cargo bench with lto = false, default (no specification regarding lto. default behavior and should be cargo-local-thin) "thin" and "fat"
false : build 12 sec
default : 12 sec
WordPiece BERT encode   time:   [12.142 µs 12.156 µs 12.175 µs]
                        change: [+2.1007% +2.2547% +2.4142%] (p = 0.00 < 0.05)
                        Performance has regressed.
WordPiece BERT encode batch
                        time:   [3.7072 ms 3.7164 ms 3.7236 ms]
                        change: [-2.2301% -1.4249% -0.5755%] (p = 0.00 < 0.05)
                        Change within noise threshold.
WordPiece Train vocabulary (small)
                        time:   [141.81 ms 142.94 ms 145.22 ms]
                        change: [-2.8931% -0.2770% +2.0800%] (p = 0.84 > 0.05)
                        No change in performance detected.
WordPiece Train vocabulary (big)
                        time:   [4.6867 s 4.7063 s 4.7268 s]
                        change: [-0.3191% +0.2702% +0.8656%] (p = 0.40 > 0.05)
                        No change in performance detected.
BPE GPT2 encode         time:   [7.7663 µs 7.7825 µs 7.7914 µs]
                        change: [-2.7402% -2.2930% -1.8826%] (p = 0.00 < 0.05)
                        Performance has improved.
BPE GPT2 encode batch   time:   [4.6418 ms 4.6597 ms 4.6882 ms]
                        change: [-1.2657% -0.5037% +0.2566%] (p = 0.21 > 0.05)
                        No change in performance detected.
BPE GPT2 encode, no cache
                        time:   [13.053 µs 13.129 µs 13.222 µs]
                        change: [-0.0858% +0.3457% +0.7477%] (p = 0.14 > 0.05)
                        No change in performance detected.
BPE GPT2 encode batch, no cache
                        time:   [3.6745 ms 3.6820 ms 3.6898 ms]
                        change: [-1.3955% -0.9265% -0.3584%] (p = 0.00 < 0.05)
                        Change within noise threshold.
BPE Train vocabulary (small)
                        time:   [143.78 ms 144.34 ms 144.86 ms]
                        change: [+0.2108% +0.9457% +1.6400%] (p = 0.02 < 0.05)
                        Change within noise threshold.
BPE Train vocabulary (big)
                        time:   [4.8729 s 4.9115 s 4.9719 s]
                        change: [-0.5752% +0.5023% +1.8446%] (p = 0.51 > 0.05)
                        No change in performance detected.
TemplateProcessing single encode
                        time:   [636.64 ns 642.56 ns 647.92 ns]
                        change: [+0.8330% +4.1864% +7.5351%] (p = 0.01 < 0.05)
                        Change within noise threshold.
TemplateProcessing pair encode
                        time:   [1.5207 µs 1.5277 µs 1.5409 µs]
                        change: [-1.1404% +3.0586% +7.2695%] (p = 0.16 > 0.05)
                        No change in performance detected.
"thin" build 22 sec (twice default/false)
WordPiece BERT encode   time:   [11.570 µs 11.676 µs 11.771 µs]
                        change: [-4.8633% -3.8038% -2.1269%] (p = 0.00 < 0.05)
                        Performance has improved.
WordPiece BERT encode batch
                        time:   [3.6158 ms 3.6286 ms 3.6442 ms]
                        change: [-3.0030% -2.4610% -1.9659%] (p = 0.00 < 0.05)
                        Performance has improved.
WordPiece Train vocabulary (small)
                        time:   [141.00 ms 142.14 ms 143.45 ms]
                        change: [-2.6455% -1.3234% -0.0404%] (p = 0.08 > 0.05)
                        No change in performance detected.
WordPiece Train vocabulary (big)
                        time:   [4.6923 s 4.7521 s 4.8214 s]
                        change: [-0.4325% +0.9719% +2.3479%] (p = 0.24 > 0.05)
                        No change in performance detected.
BPE GPT2 encode         time:   [7.8966 µs 7.9327 µs 7.9664 µs]
                        change: [+1.8893% +2.3179% +2.8200%] (p = 0.00 < 0.05)
                        Performance has regressed.
BPE GPT2 encode batch   time:   [4.7015 ms 4.7239 ms 4.7547 ms]
                        change: [+0.9464% +1.6609% +2.4077%] (p = 0.00 < 0.05)
                        Change within noise threshold.
BPE GPT2 encode, no cache
                        time:   [13.203 µs 13.289 µs 13.353 µs]
                        change: [-0.2878% +0.2186% +0.7557%] (p = 0.42 > 0.05)
                        No change in performance detected.
BPE GPT2 encode batch, no cache
                        time:   [3.7389 ms 3.7501 ms 3.7640 ms]
                        change: [+1.5758% +2.1585% +2.7165%] (p = 0.00 < 0.05)
                        Performance has regressed.
BPE Train vocabulary (small)
                        time:   [143.49 ms 144.08 ms 144.66 ms]
                        change: [-1.2355% -0.6234% -0.0220%] (p = 0.07 > 0.05)
                        No change in performance detected.
TemplateProcessing single encode
                        time:   [633.35 ns 637.98 ns 645.59 ns]
                        change: [-2.9046% +0.4168% +3.8904%] (p = 0.82 > 0.05)
                        No change in performance detected.
TemplateProcessing pair encode
                        time:   [1.4339 µs 1.4479 µs 1.4639 µs]
                        change: [-8.7397% -4.8134% -0.6238%] (p = 0.04 < 0.05)
                        Change within noise threshold.


"fat" build 38 sec (triple default/false half more than "thin" still <1min)
WordPiece BERT encode   time:   [10.580 µs 10.607 µs 10.636 µs]
                        change: [-10.642% -9.1847% -8.1060%] (p = 0.00 < 0.05)
                        Performance has improved.
WordPiece BERT encode batch
                        time:   [3.4846 ms 3.4947 ms 3.5077 ms]
                        change: [-3.9579% -3.4479% -2.8938%] (p = 0.00 < 0.05)
                        Performance has improved.
WordPiece BERT encode batch
                        time:   [3.4846 ms 3.4947 ms 3.5077 ms]
                        change: [-3.9579% -3.4479% -2.8938%] (p = 0.00 < 0.05)
                        Performance has improved.
WordPiece Train vocabulary (big)
                        time:   [4.6387 s 4.6737 s 4.7185 s]
                        change: [-3.2964% -1.6503% -0.1037%] (p = 0.08 > 0.05)
                        No change in performance detected.
BPE GPT2 encode         time:   [7.2508 µs 7.2891 µs 7.3354 µs]
                        change: [-8.7456% -8.2161% -7.6999%] (p = 0.00 < 0.05)
                        Performance has improved.
BPE GPT2 encode batch   time:   [4.5304 ms 4.5452 ms 4.5682 ms]
                        change: [-4.5213% -3.7020% -2.9064%] (p = 0.00 < 0.05)
                        Performance has improved.
BPE GPT2 encode, no cache
                        time:   [12.380 µs 12.427 µs 12.488 µs]
                        change: [-6.6199% -6.2004% -5.7552%] (p = 0.00 < 0.05)
                        Performance has improved.
BPE GPT2 encode batch, no cache
                        time:   [3.6803 ms 3.7047 ms 3.7315 ms]
                        change: [-2.8652% -2.1123% -1.4263%] (p = 0.00 < 0.05)
                        Performance has improved.
BPE Train vocabulary (small)
                        time:   [141.97 ms 142.34 ms 142.62 ms]
                        change: [-1.6838% -1.1875% -0.7033%] (p = 0.00 < 0.05)
                        Change within noise threshold.
BPE Train vocabulary (big)
                        time:   [4.8944 s 4.9254 s 4.9673 s]
                        change: [-3.7784% -2.0750% -0.3225%] (p = 0.04 < 0.05)
                        Change within noise threshold.
TemplateProcessing single encode
                        time:   [563.54 ns 567.98 ns 573.04 ns]
                        change: [-15.170% -12.450% -9.8257%] (p = 0.00 < 0.05)
                        Performance has improved.
TemplateProcessing pair encode
                        time:   [1.4113 µs 1.4208 µs 1.4295 µs]
                        change: [-7.3345% -2.9488% +1.1690%] (p = 0.22 > 0.05)
                        No change in performance detected.

Summarizing the findings, I would have to say that lto="fat" is the way to go.
It shows either no performance regressions or some amount of gain.
Not as drastic as the OP but still relevant.
11sec to 38 sec build time is a manageable amount imo.

This PR also has the side effect of defining the release profile ([profile.release]) in Cargo.toml.
I think all in all this would be a positive change with no forseeable downsides.

@Narsil  what do you think? would you like to see more testing?

**Comment by chris-ha458** [comment]
by "you" are you referring to me or @csko ?
In case it was me, I am not sure of the need for a separate PR since it's just a one line change.
If you need it to implement modifications within setup.py,  I must say that I am yet unfamiliar with the python build process.
( I have still been wrapping my head around the rust build process, and for debugging i usually just used 
cargo build cargo test etc)

**Review by Narsil — APPROVED** [review]
Can't find simple options fast enough.

Let's to it this way I'll figure out a way to speed things up locally later.

**Pull request merged**
