### PR TITLE
node: add tokenizer truncation / padding bindings

### PR DESCRIPTION
**Pull request by Pierrci**
I'm adding bindings I need for question answering in Node. For now:
- `tokenizer.setTruncation`
- `tokenizer.setPadding`

### CODE REVIEW

**Comment by n1t0** [comment]
Looks really good! How do you want to handle the case where you need to disable either the truncation or the padding after it's been set? In Python, we do `no_padding` or `no_truncation` for example.

**Comment by Pierrci** [comment]
@n1t0 so I didn't really think about disabling padding/truncation since it was not my use case haha, but it was rather straightforward so I added `disableTruncation` and `disablePadding` methods. And that will be all for this PR.

**Comment by Pierrci** [comment]
@n1t0 and I have noooooo f****** idea of why suddenly clippy is making the CI fail, it's raising errors on code in the main rs source files that were totally fine until now!! 🤬

**Comment by Pierrci** [comment]
So the "problem" seems to come from the new Rust version 1.41.0 released today, but I think it actually behaves in 1.41 as it should have been from the start given this line in the rust CI:
https://github.com/huggingface/tokenizers/blob/6d532fedb1d3626328828304a5c39807733d2fa1/.github/workflows/rust.yml#L56

From my understanding, the `-D warnings` tells clippy to reject all warnings, which wasn't the case until now in the facts. So the possibilities are (for me):
- Fix all the clippy warnings
- Remove the `-D warnings` flag
- Pin to rust 1.40.0

wdyt @n1t0?

**Comment by Pierrci** [comment]
> So the "problem" seems to come from the new Rust version 1.41.0 released today, but I think it actually behaves in 1.41 as it should have been from the start given this line in the rust CI:
> 
> https://github.com/huggingface/tokenizers/blob/6d532fedb1d3626328828304a5c39807733d2fa1/.github/workflows/rust.yml#L56
> 
> From my understanding, the `-D warnings` tells clippy to reject all warnings, which wasn't the case until now in the facts. So the possibilities are (for me):
> 
>     * Fix all the clippy warnings
> 
>     * Remove the `-D warnings` flag
> 
>     * Pin to rust 1.40.0
> 
> 
> wdyt @n1t0?

cc @mfuntowicz since I see you got the same problem x)

**Pull request merged**
