### PR TITLE
Bump dirs from 3.0 to 4.0

### PR DESCRIPTION
**Pull request by hvaara**

### CODE REVIEW

**Comment by Narsil** [comment]
Hello thanks for this PR I'll wait for it to be non draft before reviewing, thanks for your contribution ! :)

**Comment by hvaara** [comment]
I believe the failing test was a flake. I rebased to main and force-pushed to make the tests run again.

**Review by Narsil — APPROVED** [review]
LGTM. Thanks for it !

**Comment by Narsil** [comment]
> I believe the failing test was a flake. I rebased to main and force-pushed to make the tests run again.

Yeah that happens sometimes.

**Comment by hvaara** [comment]
I updated the merge conflict.

@Narsil Is this still okay to submit?

**Comment by Narsil** [comment]
Sorry, totally forgot ! Cheers !

**Pull request merged**
